# Generated by Django 4.2.1 on 2023-05-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('workload', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data de realização')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.aluno')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.aluno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.curso')),
            ],
        ),
    ]
